BASE_URL = "https://qa-scooter.praktikum-services.ru"
COURIER_URL = f"{BASE_URL}/api/v1/courier/"
LOGIN_COURIER_URL = f"{BASE_URL}/api/v1/courier/login"
ACCEPT_ORDER_URL = f"{BASE_URL}/api/v1/orders/accept/"
CREATE_ORDER_URL = f"{BASE_URL}/api/v1/orders"
GET_ORDER_URL = f"{BASE_URL}/api/v1/orders"
TRACK_ORDER_URL = f"{BASE_URL}/api/v1/orders/track"
